version: '3.8'

services:
  api:
    image: ${DOCKER_USERNAME:-suminobraa}/ecommerce-api:latest
    container_name: ecommerce_api
    ports:
      - "8080:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - ConnectionStrings__AZURE_SQL_CONNECTIONSTRING=${AZURE_SQL_CONNECTIONSTRING}
      - ConnectionStrings__AzureStorageAccount=${AzureStorageAccount}
      - RedisCache=redis:6379
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672
      - SecretKey=${SecretKey}
      - Authentication__Google__ClientId=${ClientId}
      - Authentication__Google__ClientSecret=${ClientSecret}
      - MailSettings__UserName=${UserName}
      - MailSettings__Password=${Password}
      - VnPayConfig__TmnCode=${TmnCode}
      - VnPayConfig__HashSecret=${HashSecret}
      - VnPayConfig__BaseUrl=${BaseUrl}
      - VnPayConfig__ReturnUrl=${ReturnUrl}
      - VnPayConfig__Version=${Version}
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ecommerce-network
    restart: always

  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network
    restart: always

volumes:
  redis_data:
  rabbitmq_data:

networks:
  ecommerce-network:
    driver: bridge